### ISSUE TITLE
Major release for Vite v5

### ISSUE THREAD

**Issue by janklimo** [ElMassimo/stimulus-vite-helpers#13]
We'll need a fix for `globEager` that [got removed](https://vitejs.dev/guide/migration.html#removed-deprecated-apis).

https://github.com/ElMassimo/stimulus-vite-helpers/blob/291393717eb5957aa840fa80f55a3bc9f268d607/src/types.ts#L3

```
node_modules/stimulus-vite-helpers/dist/index.d.ts:3:54 - error TS2339: Property 'globEager' does not exist on type 'ImportMeta'.
  declare type ImportedModules = ReturnType<ImportMeta['globEager']>;
```

A quick fix but I think it'd require a major release bump.

**Comment by ElMassimo** [comment]
Hi Jan! Thanks for reporting.

Vite can make breaking changes in types in minor releases, so a minor release would be aligned with that.
