### ISSUE TITLE
Add ability to skip namespaces

### ISSUE THREAD

**Issue by CodeGradox** [ElMassimo/stimulus-vite-helpers#2]
Hi!

I'm currently working on migrating our codebase from webpacker to vite_ruby, and today I ran into a small issue.
In our app, we have namespaced our controllers by the module they belong to. Our structure looks something like this.
```
# Admin module
app/javascript/controllers/admin/frontpage/*_controller.js
app/javascript/controllers/admin/dashboard/*_controller.js

# Core module
app/javascript/controllers/core/users/*_controller.js
app/javascript/controllers/core/buildings/*_controller.js
```

With webpacker, we are able to use `require.context("path", true, /\.js$/)` to ignore the module namespace folder, but I'm having a hard time figuring out how to do the same with vite and `import.meta.globEager`. I did find a solution, but it's not elegant.

With webpacker we get users--index_controller, dashboard--edit_controller, etc.
```js
const context = require.context("controllers/admin", true, /\.js$/)
application.load(definitionsFromContext(context))
```

With vite we have to do this to achieve the same result. This is because `globEager` includes the entire path.
```js
const controllers = definitionsFromGlob(import.meta.globEager("/controllers/admin/**/*_controller.js"))
controllers.forEach(entry => {
  entry.identifier = entry.identifier.replace("admin--", "")
})
application.load(controllers)
```

It would be nice if `registerControllers` allowed us to pass in an option to skip the first `n` namespaces.
```js
const controllers = import.meta.globEager("/controllers/admin/users/index_controller.js", { skipNamespace: 0 }) // The default
// admin--users--index

const controllers = import.meta.globEager("/controllers/admin/users/index_controller.js", { skipNamespace: 1 })
// users--index
```

**Comment by ElMassimo** [comment]
Hi Magnus!

You can use a glob import in a nested directory (`controllers/admin/index.js` or `controllers/core/index.js`), which will cause the keys not to contain the namespace that you would like to ignore. Then, export the `globEager` results and import them in `controllers/index.js`, combining them to perform a single registration.

```js
import adminControllers from '~/controllers/admin'
import coreControllers from '~/controllers/core'

const controllers = { ...adminControllers, ...coreControllers }

registerControllers(application, controllers)
```

Supporting `skipNamespace` is out of scope for this 25-loc-library 😃
