### ISSUE TITLE
Match controllers without prefix

### ISSUE THREAD

**Issue by Timmitry** [ElMassimo/stimulus-vite-helpers#3]
Our project uses a convention where we have a sidecar folder for each component, containing all related files - e.g.:

```
components/button
  - component.rb
  - component.html.erb
  - component.css
  - controller.ts
```

Unfortunately, this does not work together with this package. After some digging, I found that the regex would need to be adapted from

```js
^(?:.*?(?:controllers|components)\/|\.?\.\/)?(.+)(?:[_-]controller\..+?)$
```

to

```js
^(?:.*?(?:controllers|components)\/|\.?\.\/)?(.+)(?:[_-]?controller\..+?)$
```

See https://regex101.com/r/nZEqLU/1 for an example. Would that be possible? I could spin up a PR if you want! Thank you for building Vite-Ruby, it really is a joy to work with 🙏

**Comment by ElMassimo** [comment]
Hi Tim!

Sounds reasonable to have this in the library by default as long as [currently supported patterns](https://github.com/ElMassimo/stimulus-vite-helpers/blob/main/tests/glob.spec.ts#L19) continue to work as expected.

PRs are welcome!

**Comment by Timmitry** [comment]
@ElMassimo Thank you, and of course the tests should still pass 😁👍  I opened a [PR](https://github.com/ElMassimo/stimulus-vite-helpers/pull/4)!
